<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search auto
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("auto/new", "Create auto")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "auto/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldKo" class="col-sm-2 control-label">KO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("KO", "type" => "number", "class" => "form-control", "id" => "fieldKo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Type", "size" => 30, "class" => "form-control", "id" => "fieldType")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGroupKogroup" class="col-sm-2 control-label">Group Of KOGroup</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Group_KOGroup", "type" => "number", "class" => "form-control", "id" => "fieldGroupKogroup")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
