<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("message", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Сообщение оператору
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "message/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>



<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Текст:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Text", "size" => 30, "class" => "form-control", "id" => "fieldText")) ?>
    </div>
</div>




<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Отправить", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
