<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("message/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("message/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Сообщения от КО</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>КО</th>

            <th>Текст</th>
            <th>Время отправки</th>
            <th>Координаты</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $message): ?>
            <tr>

                <td><?php echo $message->Trace_Auto_KO ?></td>


                <td><?php echo $message->Text ?></td>
            <td><?php echo $message->MessageTime ?></td>
            <td><?php echo $message->Trace_idTrace ?></td>

                <td><?php echo $this->tag->linkTo(array("message/edit/" . $message->idMessage, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("message/delete/" . $message->idMessage, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("message/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("message/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("message/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("message/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
