<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("trace", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit trace
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "trace/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldAutoKo" class="col-sm-2 control-label">Auto Of KO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Auto_KO", "type" => "number", "class" => "form-control", "id" => "fieldAutoKo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCoordinates" class="col-sm-2 control-label">Coordinates</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Coordinates", "type" => "number", "class" => "form-control", "id" => "fieldCoordinates")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMessage" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Message", "size" => 30, "class" => "form-control", "id" => "fieldMessage")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTime" class="col-sm-2 control-label">Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Time", "type" => "date", "class" => "form-control", "id" => "fieldTime")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
