

<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
   <h3> Полный отчет по движению КО </h3>


</div>

<?php echo $this->getContent() ?>

<?php
echo $this->tag->form(
    array(
        "trace/ReportTotal",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    )
);
?>



<div class="form-group">
    <label for="fieldAutoKo" class="col-sm-2 control-label">KO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Auto_KO", "type" => "number", "class" => "form-control", "id" => "fieldAutoKo")) ?>
    </div>
</div>



<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Построить отчет", "class" => "btn btn-default")) ?>
    </div>
</div>




<?php echo $this->tag->endForm(); ?>







