<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search trace
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("trace/new", "Create trace")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
echo $this->tag->form(
    array(
        "trace/search",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    )
);
?>

<div class="form-group">
    <label for="fieldIdtrace" class="col-sm-2 control-label">IdTrace</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("idTrace", "type" => "number", "class" => "form-control", "id" => "fieldIdtrace")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAutoKo" class="col-sm-2 control-label">Auto Of KO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Auto_KO", "type" => "number", "class" => "form-control", "id" => "fieldAutoKo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCoordinate" class="col-sm-2 control-label">Coordinate</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Coordinate", "size" => 30, "class" => "form-control", "id" => "fieldCoordinate")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTime" class="col-sm-2 control-label">Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Time", "size" => 30, "class" => "form-control", "id" => "fieldTime")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSpeed" class="col-sm-2 control-label">Speed</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Speed", "size" => 30, "class" => "form-control", "id" => "fieldSpeed")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
