<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php echo $this->getContent() ?>

<?php
echo $this->tag->form(
    array(
        "trace/report",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    )
);
?>



Общий отчет по

    <div class="form-group">
        <label for="fieldAutoKo" class="col-sm-2 control-label"> КО</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(array("Auto Of KO", "type" => "number", "class" => "form-control", "id" => "fieldAutoKo")) ?>
        </div>
    </div>




<?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(array("Построить отчет", "class" => "btn btn-default")) ?>
        </div>
    </div>






<?php echo $this->tag->endForm(); ?>