<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("trace/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("trace/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1> Сводный отчет по движению всех объектов </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Объект наблюдения</th>
            <th>Координаты начала движения</th>
            <th>Время начала движения</th>
            <th>Координаты конца движения</th>


            <th>Время завершения </th>
            <th>Время в пути</th>


            <!--    <th>ЧП</th> -->

        </tr>
        </thead>
        <tbody>


        <?php
        //     $x=0;
        //   print_r ($page->items );
        // echo $page->items[0]->Auto_KO;
        $i=0;
        $x=0;
      //  foreach ($page->items as $trace): //time to bidlocode
            //$x++;
            //      endforeach; //костыль так как коунт хз чо

            $x = count($page->items) - 1;

            //echo $x;
          //  $x++;
            // считаем время

            //if (($x)==$all)
            // $x--;//break;

          // if (($x-1)==$all) ) {
                // $x++;
                $diff = strtotime($page->items[$x]->Time ) - strtotime($page->items[$i]->Time);

                ?>


                <tr>
                    <td><?php echo $page->items[$i]->Auto_KO ?> </td>
                    <td> <?php echo $page->items[$i]->Coordinate ?></td>
                    <td><?php echo $page->items[$i]->Time ?></td>
                    <td> <?php echo $page->items[$x]->Coordinate ?></td>
                    <td><?php echo $page->items[$x]->Time ?></td>
                    <td><?php echo round($diff / 86400) . "д. " . round(($diff % 86400) / 3600) . "ч  " . round(($diff % 3600) / 60) . "м " . round($diff % 60) . "с"; ?></td>
                    <td><?php


                        //  foreach ($page->items[0]->Message as $CHP)
                        /*   for ($i=0;$i<$x;$i++) {
                               echo $page->items[0]->Message;
                           };
           */
                        //echo array_count_values($page->items[0]->Message);


                        ?></td>

                </tr>
                <?php
            //    $i=$x-1;
          //  }

      //  endforeach;
                ?>
        </tbody>


    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("trace/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
