<?php

$i = 0;

foreach ($page->items as $trace):


    $Coordinate[$i] = array(
        "idTrace" => $trace->idTrace,
        "Auto_KO" => $trace->Auto_KO,
        "Coordinate" => $trace->Coordinate,
        "Time" => $trace->Time,
        "Speed" => $trace->Speed,
        "Route" => $trace->Route,

    );


    $i++;
endforeach;

echo($trace->Coordinate);



file_put_contents('time.json', json_encode($Coordinate));




?>