<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("trace/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("trace/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>IdTrace</th>
            <th>Auto Of KO</th>
            <th>Coordinates</th>
            <th>Message</th>
            <th>Time</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $trace): ?>
            <tr>
                <td><?php echo $trace->idTrace ?></td>
            <td><?php echo $trace->Auto_KO ?></td>
            <td><?php echo $trace->Coordinate ?></td>
            <td><?php echo $trace->Message ?></td>
            <td><?php echo $trace->Time ?></td>

                <td><?php echo $this->tag->linkTo(array("trace/edit/" . $trace->idTrace, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("trace/delete/" . $trace->idTrace, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("trace/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
