<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<script src="http://maps.google.com/maps/api/js?sensor=true&key=AIzaSyDRy7PaS8kzgAH8Vu5bwThEzHrvHp7qbtY"></script>


<style>
    #map {
        width: 600px;
        height: 400px;
        border: solid 1px black;
    }

</style>


<script>



   var myOptions = {
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    // Создаем карту, используя установленные выше параметры
    map = new google.maps.Map(document.getElementById("map"), myOptions
    );



    // Создаём карту
 /*  var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 4,
        center: new google.maps.LatLng(0, 0),
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });
*/
    // Маркеры
    var markers = [
        ['Маркер 1', 45.21465, 65.14896],
        ['Маркер 2', 65.14896, 45.21465],
        // ...
    ];

    // Область показа маркеров
    var markersBounds = new google.maps.LatLngBounds();

  /*  for (var i = 0; i < markers.length; i++) {
        var markerPosition = new google.maps.LatLng(markers[i][1], markers[i][2]);

        // Добавляем координаты маркера в область
        markersBounds.extend(markerPosition);

        // Создаём маркер
        var marker = new google.maps.Marker({
            position: markerPosition,
            map: map,
            title: markers[i][0],
        });
    }
*/
    // Центрируем и масштабируем карту
//    map.setCenter(markersBounds.getCenter(), map.fitBounds(markersBounds));




</script>


<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("trace/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("trace/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1> Сводный отчет по движению объекта </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Объект наблюдения</th>
            <th>Координаты начала движения</th>
            <th>Время начала движения</th>
            <th>Координаты конца движения</th>


            <th>Время завершения </th>
            <th>Время в пути</th>


            <th>ЧП</th>

        </tr>
        </thead>
        <tbody>


        <?php
        //     $x=0;
        //   print_r ($page->items );
        echo $page->items[0]->Auto_KO;
        // foreach ($page->items as $trace):
        //$x++;
        //      endforeach; //костыль так как коунт хз чо

        $x = count($page->items) - 1;

        //echo $x;


        $diff = strtotime($page->items[175]->Time ) - strtotime($page->items[0]->Time);
         // считаем время


        ?>
        <tr>
            <td><?php echo $page->items[0]->Auto_KO ?> </td>
            <td> <?php echo $page->items[0]->Coordinate ?></td>
            <td><?php echo $page->items[0]->Time ?></td>
            <td> <?php echo $page->items[$x]->Coordinate ?></td>
            <td><?php echo $page->items[$x]->Time ?></td>
            <td><?php echo round($diff / 86400)."д.,".round(($diff % 86400) / 3600)."ч: ".round(($diff % 3600) / 60). "м:".round($diff % 60)."с"; ?></td>
            <td><?php


              //  foreach ($page->items[0]->Message as $CHP)
              for ($i=0;$i<$x;$i++) {
                    echo $page->items[0]->Message;
                };

                //echo array_count_values($page->items[0]->Message);


                ?></td>

        </tr>
        <?php //endforeach; ?>
        </tbody>


    </table>
</div>






<div id="map"></div>











<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("trace/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("trace/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
