<!DOCTYPE html>
<html>
    <head>




    </head>



    <body>


        <header>
 




 <div class="navbar">
  <div class="navbar-inner">
    <div class="container">


<!--

 <ul class="nav nav-tabs">
        <ul class="nav">
        <li><a href="{{ url("mail/in") }}">Входящие  </a></li>
        <li><a href="{{ url("mail/out") }}">Отправленные  </a></li>
        <li><a href="{{ url("avto/all") }}">Подвезут  </a></li>
        <li><a href="{{ url("pass/all") }}">Подвезти  </a></li>
        <li>    <a href="{{ url("/avto/my/") }}"> Мой Профиль</a>     </li>
  -->
        <!-- .nav, .navbar-search, .navbar-form, etc -->

            <a class="fa fa-save fa-3x" 0 aria-hidden="true" href="javascript:$('#body').wordExport();"></a>
            <a class="fa fa-print fa-3x" 0 aria-hidden="true" href="javascript:window.print(); void 0;"></a>





    </div>
 
    </div>
  </div>
</div>



            <!-- end navigation-block -->
        </header>



