<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("group", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create group
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "group/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldKogroup" class="col-sm-2 control-label">KOGroup</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("KOGroup", "type" => "number", "class" => "form-control", "id" => "fieldKogroup")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGroupname" class="col-sm-2 control-label">GroupName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("GroupName", "size" => 30, "class" => "form-control", "id" => "fieldGroupname")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
