<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search security
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("security/new", "Create security")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "security/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldIdsecurity" class="col-sm-2 control-label">IdSecurity</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("idSecurity", "type" => "number", "class" => "form-control", "id" => "fieldIdsecurity")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFioSecurity" class="col-sm-2 control-label">FIO Of Security</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("FIO_Security", "size" => 30, "class" => "form-control", "id" => "fieldFioSecurity")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLogin" class="col-sm-2 control-label">Login</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Login", "size" => 30, "class" => "form-control", "id" => "fieldLogin")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("Password", "size" => 30, "class" => "form-control", "id" => "fieldPassword")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
